### ISSUE TITLE
Matplotlib button6 and button7 produces KeyError in Linux

### ISSUE THREAD

**Issue by alguerre** [alguerre/TrackEditor#16]
alguerre@alguerre-VirtualBox:~/Desktop/TrackEditor$ python3 src/track_editor.py 
Traceback (most recent call last):
  File "src/track_editor.py", line 112, in <module>
    MainApplication(root).pack(side='top', fill='both', expand=True)
  File "src/track_editor.py", line 57, in __init__
    toolbar.children['!button6'].pack_forget()  # configure subplots
KeyError: '!button6'

The script issue_14_16.sh has a workaround for Linux launch.

**Comment by alguerre** [comment]
This issue has been reproduced in windows when updating matplotlib.
